image: gitpod/workspace-node
tasks:
  - name: Install Hugo and Dependencies
    before: 
      wget https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_Linux-64bit.deb
      sudo dpkg -i hugo_extended_0.101.0_Linux-64bit.deb
      npm install
      sudo apt install git-restore-mtime
    init: git restore-mtime --force
    command: hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0
ports:
  - port: 1313
    onOpen: open-browser
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
vscode:
  extensions:
    - bungcip.better-toml
    - budparr.language-hugo-vscode
    - eliostruyf.vscode-front-matter
    - valentjn.vscode-ltex
